# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "A homebrew cask for installing filecoin-project/lotus on MacOS"
  homepage "https://filecoin.io"
  version "1.22.1"
  license "MIT"

  depends_on "hwloc"

  on_macos do
    url "https://github.com/filecoin-project/lotus/releases/download/v1.22.1/lotus_v1.22.1_darwin_all.tar.gz"
    sha256 "8e985f668f3f02fa3610690fd34b904ffdc5f29420b215c16bc4607c1646a7e6"

    def install
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/filecoin-project/lotus/releases/download/v1.22.1/lotus_v1.22.1_linux_amd64.tar.gz"
      sha256 "0ea5371a6b814137083417e78a8f35979d5dffcc144d9fa59a1785c1fb4853d1"

      def install
        bin.install "lotus"
        bin.install "lotus-miner"
        bin.install "lotus-worker"
      end
    end
  end

  test do
    system "#{bin}/lotus --version"
    system "#{bin}/lotus-miner --version"
    system "#{bin}/lotus-worker --version"
  end
end
