# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "A homebrew cask for installing filecoin-project/lotus on MacOS"
  homepage "https://filecoin.io"
  version "1.20.4"
  license "MIT"

  depends_on "hwloc"

  on_macos do
    url "https://github.com/filecoin-project/lotus/releases/download/v1.20.4/lotus_v1.20.4_darwin_all.tar.gz"
    sha256 "7e4385ab1c23593aafb75429b21a58ab2c6409e72817774afe2df2ef8b56c4e0"

    def install
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/filecoin-project/lotus/releases/download/v1.20.4/lotus_v1.20.4_linux_amd64.tar.gz"
      sha256 "20c4c3d328031fed562fbfc7f4b14371b19349314fff2db039cc8948bcb3cb19"

      def install
        bin.install "lotus"
        bin.install "lotus-miner"
        bin.install "lotus-worker"
      end
    end
  end

  test do
    system "#{bin}/lotus --version"
    system "#{bin}/lotus-miner --version"
    system "#{bin}/lotus-worker --version"
  end
end
