# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "A homebrew cask for installing filecoin-project/lotus on MacOS"
  homepage "https://filecoin.io"
  version "1.28.2"
  license "MIT"

  depends_on "hwloc"

  on_macos do
    url "https://github.com/filecoin-project/lotus/releases/download/v1.28.2/lotus_v1.28.2_darwin_all.tar.gz"
    sha256 "fe817e6023e01b7f92bffa797aba721a673a9909b15ccad0eec721426f2efc21"

    def install
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/filecoin-project/lotus/releases/download/v1.28.2/lotus_v1.28.2_linux_amd64.tar.gz"
        sha256 "8d052a150659d66b1a9e816870cd011f9a7cef10f6677a0dfce03a00410b59c5"

        def install
          bin.install "lotus"
          bin.install "lotus-miner"
          bin.install "lotus-worker"
        end
      end
    end
  end

  test do
    system "#{bin}/lotus --version"
    system "#{bin}/lotus-miner --version"
    system "#{bin}/lotus-worker --version"
  end
end
